### ISSUE TITLE
Agregar tox-environment docs a travis

### ISSUE THREAD

**Issue by leliel12** [juancgvazquez/skmrifilter#13]
```yaml
    - python: 3.8
          env: TOXENV=py38
          dist: xenial
          sudo: true
```

No les va  andar ese environment en travis (**Asi como no me anda en mi maquina**) por que estan la carpeta `docs/source/_static`.
Git no versio carpeta vacias, asi que van a tener que agregar un archivo `emptyfile` adentro.
